### ISSUE TITLE
モバイルではとことんキャッシュする

### ISSUE THREAD

**Issue by Petitsurume** [sagume/Misskey-Web#26]
# 詳細
AppCache使ったらTL最新にするときに無駄な通信が少なくなって幸せになりそう
<http://labs.vividworks.jp/iphoneipadiosにおけるhtml5のmanifestのキャッシュ挙動について-vol-1/>

**Comment by otofune** [comment]
@Petitsurume 
現在、非推奨になっていますので実装されません。
https://developer.mozilla.org/ja/docs/Web/HTML/Using_the_application_cache

**Comment by Petitsurume** [comment]
現時点でモバイルではAppCacheが最善では
