### ISSUE TITLE
ユーザー画面word-breakが死んでる（多分）

### ISSUE THREAD

**Issue by potato4d** [sagume/Misskey-Web#47]
# ブラウザ

Chrome v52

# デスクトップ版 or モバイル版

ですくとっぷ

# 問題の詳細

![2016-08-23 2 26 49](https://cloud.githubusercontent.com/assets/6993514/17864460/28090b26-68d9-11e6-905f-b8b208a40200.png)

**Comment by otofune** [comment]
word-breakはあるっぽいが内容によって挙動が違う  
「あああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああああ」だとしっかり改行される  
「！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！」だと死ぬ  
「aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa」でも死ぬ  

max-widthが記述になさそうなのが原因かもしれない
