### ISSUE TITLE
なーんかデザインこわれる

### ISSUE THREAD

**Issue by otofune** [sagume/Misskey-Web#61]
いろいろ依存パッケージアップデートした後、cssをdiffしたら白色部分が黒い色になってて欝になった
どこまで影響があるのかわからんから要検証

**Comment by otofune** [comment]
![oma](https://cloud.githubusercontent.com/assets/15062473/18415846/c3490732-783b-11e6-8757-3860e04b8a84.PNG)
![nma](https://cloud.githubusercontent.com/assets/15062473/18415848/c4ab6908-783b-11e6-8008-4239f2eafdd8.PNG)
![omh](https://cloud.githubusercontent.com/assets/15062473/18415853/f3344678-783b-11e6-847a-076fa79b20d4.PNG)
![nmh](https://cloud.githubusercontent.com/assets/15062473/18415854/f48898b2-783b-11e6-9c0c-328367b69a17.PNG)

**Comment by Petitsurume** [comment]
#9

**Comment by otofune** [comment]
lessの機能で自動生成してるっぽく、それの処理の問題
https://misskey.link/ のカラーだったら普通に使えた
https://github.com/sagume/Misskey-Web/blob/master/src/sites/desktop/common/styles/ui.less#L187
http://lesscss.org/functions/#color-operations-contrast
